const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);const loginView=document.querySelector("#loginView"),appView=document.querySelector("#appView"),msg=document.querySelector("#authMsg"),status=document.querySelector("#status");async function init(){const {data}=await sb.auth.getSession();show(data.session)}function show(session){if(session){loginView.classList.add("hidden");appView.classList.remove("hidden");loadNews();loadMedia();loadSocial()}else{loginView.classList.remove("hidden");appView.classList.add("hidden")}}document.querySelector("#login").onclick=async()=>{msg.textContent="";const {data,error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error){msg.textContent=error.message}else show(data.session)};document.querySelector("#logout").onclick=async()=>{await sb.auth.signOut();show(null)};sb.auth.onAuthStateChange((_e,s)=>show(s));
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));document.querySelector("#"+b.dataset.panel).classList.remove("hidden")});
document.querySelector("#newsForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),row={title:f.get("title"),category:f.get("category"),location:f.get("location"),featured_image_url:f.get("featured_image_url"),excerpt:f.get("excerpt"),content:f.get("content"),published:f.get("published")==="on",published_at:f.get("published")==="on"?new Date().toISOString():null};const {error}=await sb.from("news").insert(row);status.textContent=error?error.message:"Article published";if(!error){e.target.reset();e.target.published.checked=true;loadNews()}};
async function loadNews(){const box=document.querySelector("#newsList"),{data,error}=await sb.from("news").select("*").order("created_at",{ascending:false});if(error){box.textContent=error.message;return}box.innerHTML=(data||[]).map(n=>`<div class="item"><div class="grow"><b>${esc(n.title)}</b><small>${n.published?"Published":"Draft"} · ${new Date(n.created_at).toLocaleString()}</small></div><button class="delete" onclick="deleteNews('${n.id}')">Delete</button></div>`).join("")||"<p>No articles yet.</p>"}
window.deleteNews=async id=>{if(!confirm("Delete this article?"))return;await sb.from("news").delete().eq("id",id);loadNews()};
document.querySelector("#mediaForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),file=document.querySelector("#mediaFile").files[0];if(!file)return;status.textContent="Uploading…";const ext=file.name.split(".").pop().toLowerCase(),path=`${crypto.randomUUID()}.${ext}`,bucket=f.get("type");let up=await sb.storage.from(bucket).upload(path,file,{upsert:false});if(up.error){status.textContent=up.error.message;return}const {data:url}=sb.storage.from(bucket).getPublicUrl(path);const {error}=await sb.from("media").insert({title:f.get("title"),caption:f.get("caption"),type:f.get("type"),file_url:url.publicUrl,storage_path:path,published:f.get("published")==="on"});status.textContent=error?error.message:"Uploaded";if(!error){e.target.reset();loadMedia()}};
async function loadMedia(){const box=document.querySelector("#mediaList"),{data,error}=await sb.from("media").select("*").order("created_at",{ascending:false});if(error){box.textContent=error.message;return}box.innerHTML=(data||[]).map(m=>`<div class="item">${m.type==="videos"?`<video src="${esc(m.file_url)}"></video>`:`<img src="${esc(m.file_url)}">`}<div class="grow"><b>${esc(m.title)}</b><small>${m.type} · ${m.published?"Published":"Draft"}</small></div><button class="delete" onclick="deleteMedia('${m.id}','${esc(m.storage_path)}','${m.type}')">Delete</button></div>`).join("")||"<p>No media yet.</p>"}
window.deleteMedia=async(id,path,type)=>{if(!confirm("Delete this media?"))return;await sb.from("media").delete().eq("id",id);await sb.storage.from(type).remove([path]);loadMedia()};const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));init();
document.querySelector("#socialForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const row={name:f.get("name"),platform:f.get("platform"),url:f.get("url"),sort_order:Number(f.get("sort_order")||0),enabled:f.get("enabled")==="on"};const {error}=await sb.from("social_links").insert(row);status.textContent=error?error.message:"Social link saved";if(!error){e.target.reset();e.target.enabled.checked=true;e.target.sort_order.value=1;loadSocial()}};
async function loadSocial(){const box=document.querySelector("#socialList");if(!box)return;const {data,error}=await sb.from("social_links").select("*").order("sort_order",{ascending:true});if(error){box.textContent=error.message;return}box.innerHTML=(data||[]).map(x=>`<div class="item"><div class="grow"><b>${esc(x.name)}</b><small>${esc(x.platform)} · ${x.enabled?"Visible":"Hidden"} · ${esc(x.url)}</small></div><button class="delete" onclick="deleteSocial('${x.id}')">Delete</button></div>`).join("")||"<p>No social links yet.</p>"}
window.deleteSocial=async id=>{if(!confirm("Delete this social link?"))return;await sb.from("social_links").delete().eq("id",id);loadSocial()};
